CREATE TABLE IF NOT EXISTS categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS initiators (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          TEXT,
    category_id         BIGINT NOT NULL,
    confirmed_requests  INT NOT NULL,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT NOT NULL,
    paid                BOOLEAN NOT NULL,
    title               TEXT,
    views               BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               TEXT
);

CREATE TABLE IF NOT EXISTS compilation_to_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL
);