
CREATE TABLE IF NOT EXISTS categories (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS initiators (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation          TEXT,
    category_id         BIGINT NOT NULL,
    confirmed_requests  INT NOT NULL,
    event_date          TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id        BIGINT NOT NULL,
    paid                BOOLEAN NOT NULL,
    title               TEXT,
    views               BIGINT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pinned              BOOLEAN NOT NULL,
    title               TEXT
);

CREATE TABLE IF NOT EXISTS compilation_to_events (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_id      BIGINT NOT NULL,
    event_id            BIGINT NOT NULL
);

DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE IF NOT EXISTS users(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(254) NOT NULL,
    email VARCHAR(254) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS categories CASCADE;

CREATE TABLE IF NOT EXISTS categories (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS events CASCADE;

CREATE TABLE IF NOT EXISTS events (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation TEXT NOT NULL,
    category BIGINT NOT NULL,
    description TEXT NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    location BIGINT NOT NULL,
    initiator BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    title TEXT NOT NULL,
    state VARCHAR(10),
    views BIGINT DEFAULT 0
);

DROP TABLE IF EXISTS locations CASCADE;

CREATE TABLE IF NOT EXISTS locations (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lat NUMERIC NOT NULL,
    lon NUMERIC NOT NULL
);

DROP TABLE IF EXISTS requests CASCADE;

CREATE TABLE IF NOT EXISTS requests (
    id  BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event BIGINT NOT NULL,
    requester BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL
);
